auto: true
server: true
permalink: "/:year/:month/:day/:title"
baseurl: "http://ghostbar.co"
name: 'GHOSTBAR'
description: 'Random thoughts on technology and hacking written by Jose Luis Rivas'
pygments: true
markdown: rdiscount
exclude:
- .gitignore
- README.md

prose:
  rooturl: "_posts"
  metadata: 
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: ghostbar
      author: Jose Luis Rivas
      categories:
      - articles
